version: '3.4'
services:
  baserow:
    container_name: baserow
    image: 'baserow/baserow:1.26.1'
    environment:
      - "BASEROW_PUBLIC_URL=http://127.0.0.1:80"
    volumes:
      - 'baserow_data:/baserow/data'
volumes:
  baserow_data: null
